version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/capstone
hooks:
  AfterInstall:
   - location: .scripts/install_app_dependencies
     timeout: 300
  ApplicationStart:
   - location: .scripts/start_server
     timeout: 300
